### ISSUE TITLE
Jupyter core should require a higher version

### ISSUE THREAD

**Issue by goanpeca** [conda-forge/jupyter_client-feedstock#35]
The current recipe is not enforcing `jupyter_core > 4.6` and it seems to install 4.4 by default for aarch64 which results in errors.

```
{% set version = "5.3.4" %}

package:
  name: jupyter_client
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-{{ version }}.tar.gz
  sha256: 60e6faec1031d63df57f1cc671ed673dced0ed420f4377ea33db37b1c188b910

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - jupyter-kernel = jupyter_client.kernelapp:main
    - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
    - jupyter-run = jupyter_client.runapp:main

requirements:
  host:
    - pip
    - python
  run:
    - entrypoints
    - jupyter_core    # THIS SHOULD BE DIFERENT?
    - python
    - python-dateutil >=2.1
    - pywin32  # [win]
    - pyzmq >=13
    - tornado >=4.1
    - traitlets

test:
  requires:
    - ipykernel
    - ipython
    - mock
    - pytest
  imports:
    - jupyter_client
  commands:
    - jupyter kernelspec list
    - jupyter run -h

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: jupyter_client contains the reference implementation of the Jupyter protocol.
  dev_url: https://github.com/jupyter/jupyter_client
  doc_url: https://jupyter-client.readthedocs.io/en/stable/
  doc_source_url: https://github.com/jupyter/jupyter_client/tree/master/docs

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - ocefpaf
    - carreau
    - SylvainCorlay
    - bollwyvl
```

@ccordoba12
